config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'home#index', as: 'index'
  get '/compliments', to: 'home#compliments', as: 'compliments'
  get '/contact', to: 'home#contact', as: 'contact'
  get '/resume', to: 'home#resume', as: 'resume'
  get '/work', to: 'home#work', as: 'work'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/compliments.html.erb
<%= render "shared/header", title: t('compliments') %>
<div class="m-4 lg:m-7">
  <h3>
    I am very lucky to have worked with a lot of wonderful humans. Some of them have said very kind things about me.
  </h3>
  <br />
  <div>
    <%= image_tag('brag-student.png', alt:"email from a student that reads, I hope this email finds you well and in good
    spirits. As my time at LEARN Academy comes to an end, I am grateful for your guidance as a mentor for this
    internship and the whole LEARN experience. From day one, your guidance in understanding the complex coding
    challenges and your emphasis on collaboration and growth as a junior developer has been invaluable. I want to than
    the entire LEARN Academy team for fostering a supportive and inclusive environment. So thank you again, Sarah! The
    knowledge and skills I've gained under your guidance will stay with me throughout mny career. I'm incredibly
    grateful for the opportunity to work with you and i look forward to staying connected.", class: 'mx-auto border') %>
  </div>
</div>

app/views/home/contact.html.erb
<%= render "shared/header", title: t('contact') %>
<div class="m-4 lg:m-7">
  <h3 class="text-xl my-1">I would love to connect with you!</h3>
  <br />
  <p>You can reach me on LinkedIn</p>
  <p>Send me an email at sproctor@gmail.com</p>
  <br />
  <p>Or fill our the form below.</p>
  <div class="my-2">
    <%= form_with do |form| %>
      <div class="lg:flex">
        <div class="lg:w-1/3 lg:mr-1">
          <%= form.label :first_name, "First Name", class: "font-bold mb-1 md:mb-0 pr-4" %>
          <%= form.text_field :first_name, class: "mt-1 w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
        </div>
        <div class="lg:w-1/3">
          <%= form.label :last_name, "Last Name", class: "block font-bold mb-1 md:mb-0 pr-4" %>
          <%= form.text_field :last_name, class: "mt-1 block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
        </div>
      </div>
      <div class="lg:w-2/3">
        <%= form.label :email, "Email", class: "block font-bold mb-1 md:mb-0 pr-4" %>
        <%= form.text_field :email, class: "mt-1 block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
        <%= form.label :message, "Message", class: "block font-bold mb-1 md:mb-0 pr-4" %>
        <%= form.text_area :message, class: "mt-1 block w-full rounded-md shadow-sm focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
      </div>
        <%= form.submit "Send Email", class: "my-2 p-2 font-bold rounded-md border border-black hover:cursor-pointer bg-gray-100" %> 
    <% end %>
  </div>
</div>


 

app/views/home/index.html.erb
<% programming = [{icon: 'devicon-javascript-plain', name: 'JavaScript'}, {icon: 'devicon-react-original', name:
'React'}, {icon: 'devicon-react-original', name: 'React.js'}, {icon: 'devicon-ruby-plain', name: 'Ruby'}, {icon:
'devicon-rails-plain', name: 'Ruby on Rails'}, {icon: 'devicon-postgresql-plain', name: 'PostgreSQL'}, {icon:
'devicon-tailwindcss-original', name: 'Tailwind'}, {icon: 'devicon-bootstrap-plain', name: 'Bootstrap'}, {icon:
'devicon-reactbootstrap-original', name: 'Reactstrap'}, {icon: 'devicon-jest-plain', name: 'Jest'}, {icon:
'devicon-rspec-plain', name: 'RSpec'}] %> <% tech = [{icon: 'devicon-git-plain', name: 'Git'}, {icon:
'devicon-github-original', name: 'GitHub'}, {icon: 'devicon-githubactions-plain', name: 'GitHub Actions'}, {icon:
'devicon-homebrew-plain', name: 'Homebrew'}, {icon: 'devicon-postman-plain', name: 'Postman'}, {icon:
'devicon-heroku-original', name: 'Heroku'}] %> <% productivity = [{icon: 'devicon-notion-plain', name: 'Notion'}, {icon:
'devicon-trello-plain', name: 'Trello'}, {icon: 'devicon-canva-original', name: 'Canva'}, {icon: 'devicon-slack-plain',
name: 'Slack'}] %>

<div class="bg-gray-100"><%= image_tag('logo.png', alt:'Sarah Proctor logo', class: 'p-4 mx-auto') %></div>
<div class="m-4 lg:m-7">
  <h3 class="text-xl my-1">Hi there, I'm Sarah 👋</h3>
  <div>
    I am passionate about the art of crafting clean, readable, and efficient code. For the last five years I have been
    leading a React.js and Ruby on Rails web development bootcamp into full-stack development. I am excited to leverage
    my extensive troubleshooting skills, agile project management methodologies, and technical experience to create
    effective software solutions.
  </div>
  <br />
  <h3 class="text-xl my-3">Skills and Competencies</h3>
  <h3 class="text-xl my-1">Programming</h3>
  <div>
    <% programming.map do |skill| %>
    <span class="pr-3"><i class="<%= skill[:icon] %> pr-1"></i><%= skill[:name] %></span>
    <% end %>
  </div>
  <br />
  <h3 class="text-xl my-1">Technical</h3>
  <div>
    <% tech.map do |skill| %>
    <span class="pr-3"><i class="<%= skill[:icon] %> pr-1"></i><%= skill[:name] %></span>
    <% end %>
  </div>
  <br />
  <h3 class="text-xl my-1">Productivity</h3>
  <div>
    <% productivity.map do |skill| %>
    <span class="pr-3"><i class="<%= skill[:icon] %> pr-1"></i><%= skill[:name] %></span>
    <% end %>
  </div>
  <br />
  <h3 class="text-xl my-1">Work</h3>
  <br />
  <h3 class="text-xl my-1">Hobbies and Interests</h3>
</div>

app/views/home/resume.html.erb
<%= render "shared/header", title: t('resume') %>
<div class="m-4 lg:m-7"">Resume</div>

app/views/home/work.html.erb
<%= render "shared/header", title: t('work') %>
<div class="m-4 lg:m-7">
  <h3>My Jobs</h3>
  <h3>Volunteer Work</h3>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <title>Sarah Proctor</title>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %> <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track":
    "reload" %> <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> <%= javascript_importmap_tags %>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
  </head>
  <body class="font-montserrat">
    <div data-controller="navbar" class="fixed w-screen"><%= render partial: '/shared/navigation' %></div>
    <main class="pt-16"><%= yield %></main>
    <div><%= render partial: '/shared/footer' %></div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="m-4 w-full mx-auto md:pt-8">
  <hr class="my-4 border-gray-200" />
  <div class="md:flex md:justify-between text-gray-500">
    <div class="text-center py-5 md:px-5 md:inline">
      <div class="md:inline">Handcrafted in Ruby on Rails by</div>
      <div class="md:inline">Sarah Proctor | &copy; 2024</div>
    </div>
    <ul class="flex justify-center mb-6 sm:mb-0 dark:text-gray-500">
      <li>
        <%= link_to 'contact', class: 'me-4' do %>
        <i class="fa fa-regular fa-envelope fa-2x p-2"></i>
        <% end %>
      </li>
      <li>
        <%= link_to 'https://www.linkedin.com/in/sarahproctor-dev/', target: :blank, class: 'me-4' do %>
        <i class="fa fa-brands fa-linkedin fa-2x p-2"></i>
        <% end %>
      </li>
      <li></li>
      <li>
        <%= link_to 'https://github.com/sjproctor', target: :blank, class: 'me-4' do %>
        <i class="fa fa-brands fa-github fa-2x p-2"></i>
        <% end %>
      </li>
    </ul>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="flex justify-center bg-gray-100 py-8 mx-auto mb-10">
  <h1 class="font-gistesy text-4xl lg:text-7xl"><%= local_assigns[:title] %></h1>
</div>

app/views/shared/_navigation.html.erb
<nav class="bg-white">
  <div class="md:flex md:justify-between" data-target="navbar.content">
    <%= link_to image_tag('small-logo.png', alt:'Sarah Proctor logo', class: 'px-4 md:h-16 hidden md:block'), root_path
    %>
    <div class="p-3">
      <button
        data-collapse-toggle="navbar-default"
        type="button"
        class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
        aria-controls="navbar-default"
        aria-expanded="false"
        data-action="click->navbar#toggle"
      >
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
          <path
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M1 1h15M1 7h15M1 13h15"
          />
        </svg>
      </button>
    </div>
    <div class="hidden w-full md:contents md:w-auto" id="navbar-default" data-navbar-target="content">
      <ul
        class="font-medium flex flex-col p-4 md:p-0 mt-4 rounded-lg md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0"
      >
        <li class="block py-3 px-1 xl:px-2 border-b md:border-none">
          <%= link_to 'My Work', work_path, class: 'block rounded' %>
        </li>
        <li class="block py-3 px-1 xl:px-2 border-b md:border-none">
          <%= link_to 'Contact', contact_path, class: 'block rounded' %>
        </li>
        <li class="block py-3 px-1 xl:px-2 border-b md:border-none">
          <%= link_to 'Compliments', compliments_path, class: 'block rounded' %>
        </li>
        <li class="block py-3 px-1 xl:px-2 border-b md:border-none">
          <%= link_to 'Resume', resume_path, class: 'block rounded' %>
        </li>
        <li class="block py-3 px-1 xl:px-2 border-b md:border-none">
          <%= link_to 'Home', root_path, class: 'block rounded' %>
        </li>
      </ul>
    </div>
  </div>
</nav>